# Generated by Django 4.2.28 on 2026-03-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigments', '0002_rename_assigments_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment_submissions',
            old_name='assigment',
            new_name='assignment',
        ),
        migrations.RenameField(
            model_name='assignment_submissions',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='assignments',
            old_name='team_id',
            new_name='team',
        ),
    ]
