# Generated by Django 4.2.28 on 2026-03-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assigments', '0003_assignments_create_at_assignments_delete_at_and_more'),
        ('assigments', '0003_rename_assigment_assignment_submissions_assignment_and_more'),
    ]

    operations = [
    ]
