# Generated by Django 4.2.28 on 2026-03-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assigments', '0004_merge_20260306_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='delete_at',
        ),
        migrations.RemoveField(
            model_name='assignments',
            name='update_at',
        ),
        migrations.AddField(
            model_name='assignment_submissions',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignments/'),
        ),
    ]
